language: android
android:
  components:
    - tools
    - platform-tools
    # Tools appears twice on purpose as itâ€™s required to get the newest Android SDK tools
    - tools

    # The BuildTools version used by this project
    - build-tools-29.0.3
    # The SDK version used to compile this project
    - android-29

    # Additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

    # Emulator to use for UI tests
    - sys-img-armeabi-v7a-android-25
jdk:
  - oraclejdk11
before_install:
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "platforms;android-28"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
script:
  - "pushd ."
  - "cd browser-sign-in"
  - "./gradlew clean build test"
  - "popd"
  - "cd custom-sign-in"
  - "./gradlew clean build test"
