[versions]
gradle = "7.3.0"
kotlin-gradle-plugin = "1.7.10"
min-sdk = "23"
compile-sdk = "31"
target-sdk = "31"
desugar-jdk = "1.1.6"

android-appcompat = "1.5.1"
android-material = "1.6.1"
android-navigation = "2.5.2"
android-constraintlayout = "2.1.4"
lifecycle-viewmodel-ktx = "2.5.1"
activity-ktx = "1.6.0"

okta-bom = "1.1.0"

kotlin-stdlib = "1.7.10"
timber = "5.0.1"

# Testing lib versions
junit = "4.13.2"
jackson = "2.13.4"
truth = "1.1.3"
androidx-test = "1.4.0"
androidx-test-orchestrator = "1.4.1"
androidx-test-espresso = "3.4.0"
androidx-test-ext = "1.1.3"
androidx-test-fragment = "1.5.3"
androidx-test-uiautomator = "2.2.0"
okta-http-okhttp = "1.3.1"
okta-management-sdk = "8.2.2"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-gradle-plugin" }
desugar-jdk = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk" }

android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "android-appcompat"}
android-material = { module = "com.google.android.material:material", version.ref = "android-material" }
android-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "android-navigation" }
android-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "android-navigation" }
android-navigation-safe-args = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "android-navigation" }
android-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "android-constraintlayout" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity-ktx" }

okta-bom = { module = "com.okta.kotlin:bom", version.ref = "okta-bom" }
okta-auth-foundation-bootstrap = { module = "com.okta.kotlin:auth-foundation-bootstrap" }
okta-web-authentication-ui = { module = "com.okta.kotlin:web-authentication-ui" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin-stdlib" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Testing libs
junit = { module = "junit:junit", version.ref = "junit" }
jackson-dataformat-yml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }

androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso"}
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso"}
androidx-test-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidx-test-espresso"}
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }
androidx-test-fragment = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-test-fragment" }
androidx-test-navigation = { module = "androidx.navigation:navigation-testing", version.ref = "android-navigation" }
androidx-test-orchestrator = { module = "androidx.test:orchestrator", version.ref = "androidx-test-orchestrator" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-test-uiautomator" }

okta-management-sdk = { module = "com.okta.sdk:okta-sdk-impl", version.ref = "okta-management-sdk" }
okta-http-okhttp = { module = "com.okta.commons:okta-http-okhttp", version.ref = "okta-http-okhttp" }

[bundles]
# Common android imports
android = [
    "android-appcompat",
    "android-material",
    "android-navigation-ui",
    "android-navigation-fragment",
    "android-constraintlayout",
    "lifecycle-viewmodel-ktx",
    "activity-ktx",
]
android-instrumentation-testing = [
    "androidx-test-core",
    "androidx-test-core-ktx",
    "androidx-test-espresso-core",
    "androidx-test-espresso-contrib",
    "androidx-test-espresso-intents",
    "androidx-test-ext-junit",
    "androidx-test-ext-junit-ktx",
    "androidx-test-navigation",
    "androidx-test-runner",
    "androidx-test-rules",
    "androidx-test-uiautomator",
]
okta-testing = [
    "okta-management-sdk",
    "okta-http-okhttp",
]
